- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
- src/test/java/org/ethereum/beacon/discovery/FunctionsTest.java
Simplify toString for NodeSession to make debug logs easier to read.
Add unit test to ensure the compressed and full public key formats are equivalent.
> Minor tidy ups

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManager.java
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerBuilder.java
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/network/DiscoveryServer.java
- src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryClientImpl.java
- src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryServer.java
- src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryServerImpl.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/mock/DiscoveryManagerNoNetwork.java
Introduces a builder to make instantiation easier in the standard case.
Report port conflicts and other startup errors back to the caller of start.
Add integration test to ensure ping and findNodes works in a simple case.
> API improvements

- src/main/java/org/ethereum/beacon/discovery/message/handler/NodesHandler.java
- src/main/java/org/ethereum/beacon/discovery/packet/AuthHeaderMessagePacket.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/AuthHeaderMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaInterpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorageFactoryImpl.java
- src/main/java/org/ethereum/beacon/discovery/util/Functions.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/mock/IdentitySchemaV4InterpreterMock.java
Switches from using `assert` which is disabled in production to using return values when checking node records are valid.  Reject handshakes which are invalid correctly.
> Validate the node record is signed correctly in AuthHeaderResponse

- src/main/java/org/ethereum/beacon/discovery/message/handler/FindNodeHandler.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/NodesHandler.java
- src/main/java/org/ethereum/beacon/discovery/packet/AuthHeaderMessagePacket.java
- src/main/java/org/ethereum/beacon/discovery/packet/MessagePacket.java
- src/main/java/org/ethereum/beacon/discovery/packet/RandomPacket.java
- src/main/java/org/ethereum/beacon/discovery/packet/UnknownPacket.java
- src/main/java/org/ethereum/beacon/discovery/packet/WhoAreYouPacket.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NotExpectedIncomingPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNoNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/FunctionsTest.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/NodeBucketTest.java
The Java `assert` keyword is not enabled by default in production so we can't depend on any checks being run.  Replace those checks with either a return value where the error was handled as part of business logic or a `Preconditions` call where the check is expected to always pass and any failures indicate developer error.
> Remove assert usage in favour of either return values or precondition checks

- src/main/java/org/ethereum/beacon/discovery/message/handler/NodesHandler.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
When a `FINDNODE` request was sent that didn't find any nodes, the returned `CompletableFuture` would time out instead of completing successfully.
> Ensure find nodes request completes when there are no results

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/PingHandler.java
- src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryClientImpl.java
- src/main/java/org/ethereum/beacon/discovery/schema/EnrField.java
- src/main/java/org/ethereum/beacon/discovery/schema/EnrFieldInterpreterV4.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordBuilder.java
- src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
The `tcp` and `udp`  ENR fields are used for IPv4 but also as a fallback for IPv6.  Rename the constants to just `TCP` and `UDP` so this is clearer.
> Rename TCP_V4 and UDP_V4 to TCP and UDP

- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordInfo.java
- src/test/java/org/ethereum/beacon/discovery/schema/NodeRecordInfoTest.java
`NodeRecordInfo` was incorrectly reading the `lastRetry` (time) value as the `retry` value (count of failed attempts) when deserialising.  Records are serialized and deserialised whenever they are stored to the node table.  As a result, any node in the node table with a non-zero `lastRetry` time would become eligible for deletion when it was reloaded and potentially removed from the node table.
> Fix NodeRecordInfo deserialization

- build.gradle
- gradle/versions.gradle
- src/main/java/org/ethereum/beacon/discovery/message/handler/NodesHandler.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/TestUtil.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/NodesHandlerTest.java
- src/test/java/org/ethereum/beacon/discovery/schema/NodeRecordInfoTest.java
To make it more difficult for malicious nodes to pollute our node table, verify that any nodes returned from a find nodes request are at the distance requested.
> Validate the distance of returned nodes matches what we requested

- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/AuthHeaderMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NotExpectedIncomingPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/UnknownPacketTypeByStatus.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/processor/MessageProcessor.java
We expect external peers to send us rubbish sometimes so only log those problems at debug level instead of error.
> Reduce log level for errors handling data from external sources

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystem.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeIdToSession.java
- src/main/java/org/ethereum/beacon/discovery/scheduler/ExpirationScheduler.java
- src/main/java/org/ethereum/beacon/discovery/scheduler/ExpirationSchedulerFactory.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
- src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java
- src/main/java/org/ethereum/beacon/discovery/task/LiveCheckTasks.java
- src/main/java/org/ethereum/beacon/discovery/task/RecursiveLookupTasks.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/handler/NodeIdToSessionTest.java
Fixes a thread leak where a new scheduled executor was created for every `NodeSession` by reusing a single `ScheduledExecutor` across all `ExpirationScheduler` instances.
> Reuse a single thread for scheduling expirations

- src/main/java/org/ethereum/beacon/discovery/schema/EnrFieldInterpreterV4.java
- src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
Fixes ENR parsing so that fields which are unknown to the client are not considered invalid.  They are instead simply parsed as `Bytes`.
> Parse unknown fields as Bytes

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
Support listening on an IP and port that is different to the IP and port in the local ENR record. This is required when the listen IP is and any address like `0.0.0.0` or when NAT is in use and the external IP and port differ from the internal ones.
> Separate listen and advertised IP

- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
Rather than manually removing padding, use the `Encoder.withoutPadding` method.
> Use the standard withoutPadding method

- src/main/java/org/ethereum/beacon/discovery/storage/NodeBucket.java
Previously writes were synchronized but reads were not.
That doesn't satisfy the thread safety requirements of TreeSet which could lead to random exceptions, but also meant that the number of records returned by getNodeRecord could exceed the 16 node limit if nodes were added while we were iterating to make a copy.
fixes https://github.com/PegaSysEng/teku/issues/2095
> Fix synchronization in NodeBucket

- src/main/java/org/ethereum/beacon/discovery/packet/UnknownPacket.java
Check the packet data is long enough to be a WhoAreYouPacket before checking the magic start prefix.
fixes #52
> Check the length before slicing data

- src/main/java/org/ethereum/beacon/discovery/scheduler/ExpirationScheduler.java
Synchronization was used inconsistently leading to a race condition between checking `isPresent` and calling `remove`.  Just check if the removed value was null instead.
fixes #53
> Fix race condition that led to a NullPointerException

- src/main/java/org/ethereum/beacon/discovery/packet/UnknownPacket.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/UnknownPacketTagToSender.java
- src/test/java/org/ethereum/beacon/discovery/packet/UnknownPacketTest.java
Check that the message is at least 32 bytes long before trying to extract the source node ID from the first 32 bytes.
Fix for https://github.com/PegaSysEng/teku/issues/2509 once it's pulled through to Teku.
> Handle unknown messages with less than 32 bytes correctly

- build.gradle
When publishing to bintray, set the version to have the git hash instead of `-SNAPSHOT` so every commit gets a unique version on bintray.  Will save us having to do a release of discovery every time we want to pull changes into Teku, but still means Teku has a deterministic version of discovery it depends on.
> Use version with git hash in it rather than -SNAPSHOT

- src/main/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelector.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/PongHandler.java
- src/main/java/org/ethereum/beacon/discovery/processor/DiscoveryV5MessageProcessor.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelectorTest.java
Require multiple peers to confirm the same external address before the local node record is updated to include it. Select the most voted for external address if there are multiple ones to choose from.
https://github.com/PegaSysEng/teku/issues/1912
> Require multiple confirmations before updating external address

- src/main/java/org/ethereum/beacon/discovery/packet/UnknownPacket.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/UnknownPacketTagToSender.java
- src/test/java/org/ethereum/beacon/discovery/packet/UnknownPacketTest.java
caching the hash(homeNodeId) so it doesn't have to be recalculated each time a tag is decoded on a RandomPacket
resolves #66
> hash cache(homeNodeId)

- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/HandshakeMessagePacketHandler.java
Now these log entries can be found: 
> 10:25:20.703 INFO  - ID signature not valid for message [HandshakeMessagePacketImpl{header=Header{header={protocolId=discv5, version=0x0001, flag=HANDSHAKE, nonce=0x6a141a3ddab596b742dba456, authDataSize=311}, authData=HandshakeAuthData{srcNodeId=0x5d306e283c98ca27a837e418ca9574eda4295887bd2dda3b0be37efcc86d96ba, idSignature=0x1d66611047148edbae5efca5ae20af9d50698f71c6aab781fff87bca5ffcc22f32f5ed1249338692e332de4aabfcd3a8d1cb6d942bf63b71eef0eafbf6ba57c1, ephemeralPubKey=0x034941d700674968fa964499e0bbf07f9eb3498170b0d69e2abada921a2dd52a84, enrBytes=0xf8b2b840e6dacc441ca18b8684edeaff780e590503b68060acea1cc26d676e1e5216bea728c6f069f987865b1cc59644206240ce15a541194fd9b6bd256e3db2361f036201876174746e65747388ffffffffffffffff846574683290e7a75d5a00000001fffff …
> Shouldn't log with INFO when remote peer sending invalid handshake data

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/HandshakeMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryManagerTest.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/TestManagerWrapper.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManagerTest.java
When receiving invalid Handshake packet the session should be dropped I.e. another negotiation round (Random, WhoAreYou) needs to be performed.
Else the peer could be DoSed with a single invalid Handshake packet forcing to perform expensive `BLS` signature validation for free from attacker side 
When merged https://github.com/ConsenSys/teku/issues/2846
> When receiving invalid Handshake packet the session should be dropped

- .circleci/config.yml
- build.gradle
- gradle.properties
Switch over to tag based releases.  Besu is using this library now so its getting more updates and the "release every commit" approach we had been using doesn't play well with HyperLedger.  So to avoid having too many versions published to the repo and still make releases really easy, switch to tag based releases.
Builds on #90
> Switch to tag based releases

- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordFactory.java
- src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
Added a new method, `NodeRecordFactory.fromEnr(String enr)`, that automatically handles the enr: prefix.
Fixes #99
> Added NodeRecordFactory.fromEnr method

- .circleci/config.yml
So that builds work for external contributors, remove the docker hub credentials and context.  Downloads of docker images may wind up being throttled but given the short build times and infrequent changes that's unlikely to be an issue for this project.
> Remove docker hub authentication

- src/main/java/org/ethereum/beacon/discovery/message/handler/PingHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandler.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/PingHandlerTest.java
When responding to PING messages, the PONG response should include our local ENR sequence number, not the remote peers.
This enables remote peers to detect when they need to request an updated ENR from us.
> Include our seq no in PONG messages, not remote peer's

- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/FindNodeHandler.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
- src/main/java/org/ethereum/beacon/discovery/storage/NodeBucketStorage.java
- src/main/java/org/ethereum/beacon/discovery/storage/NodeBucketStorageImpl.java
- src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorageFactory.java
- src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorageFactoryImpl.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/FindNodeHandlerTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/NodeBucketStorageImplTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/NodeBucketTest.java
When requesting distance 0 from the bucket storage, always return the latest local node info rather than a previously stored version.
> Get latest home enr

- src/main/java/org/ethereum/beacon/discovery/message/handler/NodesHandler.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/NodesHandlerTest.java
When a `NODES` message is received that contains a newer ENR for a previously discovered node, update it's record in the node table.
Note that it is not updated in the bucket storage because we haven't validated the liveness of the new ENR yet (that's done through separate liveness checks).
> Update node table when newer ENRs received from FINDNODES

- src/main/java/org/ethereum/beacon/discovery/storage/BucketEntry.java
- src/main/java/org/ethereum/beacon/discovery/storage/KBucket.java
- src/main/java/org/ethereum/beacon/discovery/storage/KBuckets.java
- src/main/java/org/ethereum/beacon/discovery/storage/NodeBucket.java
- src/test/java/org/ethereum/beacon/discovery/SimpleIdentitySchemaInterpreter.java
- src/test/java/org/ethereum/beacon/discovery/StubClock.java
- src/test/java/org/ethereum/beacon/discovery/storage/BucketEntryTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/KBucketTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/KBucketsTest.java
Add a new implementation of k-bucket storage that also handles the scheduling of liveness checks for nodes in those buckets.
Currently this isn't actually plugged in anywhere and the `LivenessChecker` is just an interface with no implementation. However this shows the most critical logic around maintaining the node table entries.
Part of #103
> Add new implementation of k-bucket storage

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManager.java
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystem.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/NodesHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/info/MultiPacketResponseHandler.java
- src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java
- src/main/java/org/ethereum/beacon/discovery/task/RecursiveLookupTask.java
- src/main/java/org/ethereum/beacon/discovery/task/RecursiveLookupTasks.java
- src/main/java/org/ethereum/beacon/discovery/task/TaskStatus.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/NodesHandlerTest.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandlerTest.java
- src/test/java/org/ethereum/beacon/discovery/task/RecursiveLookupTaskTest.java
Return the nodes found by a `findNodes` or `searchForNewPeers` request so they can be utilised even if they didn't get added to the node table (eg because it was full).
> Return found nodes

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionRequestHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/SessionLookup.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
Use the ENR supplied when initiating the request rather than requiring the peer to be present in the node table.
Still looks up the record from the node table if it is unknown (eg incoming requests).
Part of #111
> Don't assume that nodes are in the node table when sending requests

- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaInterpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordBuilder.java
- src/main/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStore.java
- src/main/java/org/ethereum/beacon/discovery/storage/NewAddressHandler.java
- src/test/java/org/ethereum/beacon/discovery/SimpleIdentitySchemaInterpreter.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelectorTest.java
- src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStoreTest.java
Provide the old node record and new address to the `NewAddressHandler` instead of old and pre-updated node records. Update utility methods to add addresses to optionally support updating the TCP port as well as the address and UDP port.
This enables client code to delay adding the UDP or TCP address info to the ENR until the external IP address is known.
#116
> Give the NewAddressHandler more flexibilty in how it updates the node record

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManager.java
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystem.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
Modifies the `DiscoverySystem.streamLiveNodes()` method to include nodes we have an `AUTHENTICATED` session with, as well as node records that are stored in the k-buckets.
This increases the set of nodes a client can consider connecting to without having to increase the bucket storage size or maintain a separate unbounded node table as before. Active sessions are already actively maintained and limited in size, but may contain a lot more nodes than are in the k-buckets because they aren't sorted by distance.
> Include active sessions in the stream of live nodes

- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
`NodeId` calculation takes a lot of time and need to be cached
> Optimization: Cache calculated NodeId in the NodeRecord

- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
The cache is now held in IdentitySchemaV4Interpreter, avoiding the need to create a new memoizing Supplier with every NodeRecord and avoiding the need to recalculate the NodeId if the same id is received from the network multiple times, which would result in multiple NodeRecord instances.
> Move the caching of NodeId to be shared across NodeRecord instances

- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordFactory.java
- src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java
Special thanks to @asanso for finding and reporting this issue 👍 
Discovery doesn't validate field key ordering and uniqueness of wire ENRs. Thus any number of ENRs with valid signature could be generated and feed to the discovery. Any severe security impact was not found. 
As per [spec](https://github.com/ethereum/devp2p/blob/master/enr.md#record-structure): 
>The key/value pairs must be sorted by key and must be unique, i.e. any key may be present only once.
> Validate ENR field keys ordering and uniqueness

- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/DefaultExternalAddressSelector.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelector.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessageHandler.java
- src/main/java/org/ethereum/beacon/discovery/processor/DiscoveryV5MessageProcessor.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/message/handler/DefaultExternalAddressSelectorTest.java
Currently there is no mean to set a fixed external advertised address if doesn't match the address seen by other discv5 nodes: the local node record is overridden due to `Ping` responses. 
This PR makes `ExternalAddressSelector` pluggable so the client code could replace the default selector with `NOOP` or any other custom implementation
> Make `ExternalAddressSelector` pluggable

- src/main/java/org/ethereum/beacon/discovery/pipeline/Envelope.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/HandlerUtil.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/BadPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/HandshakeMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/IncomingDataPacker.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessageHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NewTaskHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NextTaskHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionRequestHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/OutgoingParcelHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/PacketDispatcherHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/UnauthorizedMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/UnknownPacketTagToSender.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouSessionResolver.java
- src/main/java/org/ethereum/beacon/discovery/task/RecursiveLookupTask.java
- src/main/java/org/ethereum/beacon/discovery/util/Functions.java
A batch of minor updates: 
Performance:
- 3f2bba6f995099c346fe5bac2d2dd93df9c4a7d9: pass shared `SecureRandom` for new `NodeSession` instead of expensive creation a new instance
- 91446d7d45a80badaf3147ff25c6cb08fb522b64: use faster non-secure `Random` instead of `SecureRandom` to generate Envelope UUID which is used internally (for logging only)
- 6631150c5162805af8e0ab95248d6a4395803f31: use faster non-secure `Random` instead of `SecureRandom` to generate 'random message': there is no need for secure random here (even a static zeroes payload should not compromise the security) 
Logging: 
- c9ce3c53f35b1f3efe6603f75f2bfad21050e884: reduce logging exception noise when logging with `DEBUG` level
Hacking: 
- aa3396319a969eecca33cd294605685a5c069768: add an option to skip ENR signature …
> Misc updates: performance, logging, hacking

- build.gradle
- gradle/versions.gradle
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/message/FindNodeMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/NodesMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PingMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PongMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/TalkReqMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/TalkRespMessage.java
- src/main/java/org/ethereum/beacon/discovery/network/IncomingMessageSink.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/PipelineImpl.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/schema/EnrFieldInterpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/EnrFieldInterpreterV4.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordFactory.java
- src/main/java/org/ethereum/beacon/discovery/util/RlpUtil.java
- src/main/java/org/ethereum/beacon/discovery/util/Utils.java
- src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/message/FindNodeMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/NodesMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/PingMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/PongMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/TalkReqMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/TalkRespMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java
Switches RLP parsing from webj3 to tuweni-rlp to avoid needing to parse into an intermediate representation before creating the internal types.
> Switch to parsing RLP with tuweni-rlp instead of web3j

- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
A couple of log lines make too much unnecessary noise in log with `DEBUG` level. 
Switch them to the `TRACE` level
> Reduce verbosity for `NodeSession` debug logs

- src/main/java/org/ethereum/beacon/discovery/message/FindNodeMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/NodesMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PingMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PongMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/TalkReqMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/TalkRespMessage.java
Noticed that `FindNodeMessage` called `RlpUtil#checkComplete` but the other message types did not.
* Call `RlpUtil.checkComplete(reader)` after reading all expected values.
* For consistency:
* Rename `listReader` -> `reader` in `FindNodeMessage`.
* Remove number (`1`) from end of variable names.
> Ensure no unexpected trailing data for all message types

- src/main/java/org/ethereum/beacon/discovery/message/FindNodeMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/NodesMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PingMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PongMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/TalkReqMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/TalkRespMessage.java
- src/main/java/org/ethereum/beacon/discovery/packet/impl/HeaderImpl.java
- src/test/java/org/ethereum/beacon/discovery/TestUtil.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/message/FindNodeMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/NodesMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/PingMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/PongMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/TalkReqMessageTest.java
- src/test/java/org/ethereum/beacon/discovery/message/TalkRespMessageTest.java
- src/test/resources/geth/v5_interop_test.go
So I messed up in #150. I didn't notice that `RlpUtil#readRlpList` calls `checkComplete`. Sorry about that.
https://github.com/ConsenSys/discovery/blob/9bb8ad3942f81450fe54a78c66f0b61e58c45b0b/src/main/java/org/ethereum/beacon/discovery/util/RlpUtil.java#L39-L47
This PR will:
* Remove extraneous `checkComplete` calls.
* Add `assertRoundTrip` and `assertRejectTrailingBytes` to `TestUtil`.
* For each message type test class:
* Make the decoder object static final (and uppercase its name).
* For reusability, extract "original" message into a static final field.
* Add new `shouldRejectTrailingBytes` test.
* Replace body of `shouldRoundTrip` with `assertRoundTrip`.
Also, unrelated to the core part of this PR:
* Fix minor format issue (`TAUthData` -> `TAuthData`) in `HeaderImpl`.
* Fix a couple …
> Add shouldRejectTrailingBytes test for messages

- build.gradle
When building this project, I encountered the following issue:
```
$ ./gradlew build
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/jtraglia/Projects/jtraglia/discv5-java/build.gradle' line: 214
* What went wrong:
A problem occurred evaluating root project 'discovery'.
> Cannot invoke method contains() on null object
```
The return value of `grgit.describe` is `null` and this is causing problems.
This PR copies what Teku does in `calculateVersion`:
* https://github.com/ConsenSys/teku/blob/master/build.gradle#L938-L940
> Handle null return from grgit.describe

- src/main/java/org/ethereum/beacon/discovery/message/FindNodeMessage.java
- src/test/java/org/ethereum/beacon/discovery/message/FindNodeMessageTest.java
According to the [spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-theory.md#node-table), there are 256 buckets and 0 is reserved for our node, so a distance value can be in `[0, 256]`.
> For each `0 ≤ i < 256`, every node keeps a k-bucket for nodes of `logdistance(self, n) == I`. The Node Discovery Protocol uses `k = 16`, i.e. every k-bucket contains up to 16 node entries.
I see that this is enforced in the `KBuckets` class, but I think we should throw a decoding error if we receive a `FindNodeMessage` with an invalid distance. We could just ignore that distance, but I think we should ignore the message:
https://github.com/ConsenSys/discovery/blob/d780ba4642db8acd1a6a8253d9e86018eafb8b89/src/main/java/org/ethereum/beacon/discovery/storage/KBuckets.java#L22-L29
Also, in …
> Throw decoding exception if there's an invalid node distance

- build.gradle
- gradle/versions.gradle
- src/main/java/org/ethereum/beacon/discovery/database/HoleyList.java
- src/main/java/org/ethereum/beacon/discovery/message/FindNodeMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PingMessage.java
- src/main/java/org/ethereum/beacon/discovery/message/PongMessage.java
- src/main/java/org/ethereum/beacon/discovery/scheduler/DelegatingReactorScheduler.java
- src/main/java/org/ethereum/beacon/discovery/util/CryptoUtil.java
- src/main/java/org/ethereum/beacon/discovery/util/Functions.java
* Update errorprone to the latest version (`2.16`)
* Btw it's a little annoying that `2.16.0` isn't valid yet.
* Update the errorprone gradle plugin to the latest version.
* Do checks from [`errorprone-checks`](https://github.com/ConsenSys/errorprone-checks) (by ConsenSys).
* Like Teku, suppress the one instance of `DoNotInvokeMessageDigestDirectly`.
* Like Teku, enable a variety of experimental checks that I think are good.
* Remove disabled checks for Java 12 that were broken.
* I don't think this is an issue any more.
* Fix findings from `MissingBraces` and `UnnecessarilyFullyQualified`.
* Will fix findings from `JavaCase` in a different PR.
> Update errorprone & do ConsenSys errorprone checks

- src/main/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandler.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandlerTest.java
Well I misinterpreted [the spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#nodes-response-0x04) and thought the following sentences meant that `FindNodeResponseHandler` should ignore excess packets, instead of rejecting the response, after the allowed maximum for total.
> Implementations may place a limit on the allowed maximum for total. If exceeded, additional responses may be ignored. 
I started to "fix" it but then I noticed that it said "additional responses" and not "additional packets". So I decided to add some tests to ensure that functionality works as expected. Also, updated two things in the handler that I thought helped readability. Should we ignore additional responses after a bad response?
> Add shouldRejectInvalidTotalPackets test

- src/main/java/org/ethereum/beacon/discovery/pipeline/HandlerUtil.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/BadPacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/HandshakeMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/MessageHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NextTaskHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/PacketDispatcherHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/UnauthorizedMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouPacketHandler.java
So for these handlers, I believe these fields should be required. As a rule of thumb, if `envelope.get(FIELD)` is called in the handler, `FIELD` should be required, right? For one instance, `MessageHandler`, all of the specific message handlers (`NodesHandler`, `PingHandler`, etc) seem to assume a valid session.
> Check for more required fields

- src/main/java/org/ethereum/beacon/discovery/storage/KBuckets.java
- src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java
- src/test/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManagerTest.java
Alternative version of #164 based on [this comment](https://github.com/ConsenSys/discovery/pull/164#issuecomment-1297698736). We want to prioritize higher distances, but...
> It would be reasonable to add lower distances if we've reached MAX_DISTANCE though.
This PR does exactly that.
> Lookup lower distances if there's space

- src/main/java/org/ethereum/beacon/discovery/database/ExpirationSet.java
- src/main/java/org/ethereum/beacon/discovery/storage/KBucket.java
- src/main/java/org/ethereum/beacon/discovery/storage/KBuckets.java
- src/test/java/org/ethereum/beacon/discovery/database/ExpirationSetTest.java
Simplify and optimise `ExpirationSet` by using guava cache. Fixes a bug where the newest item was removed when the set was full rather than the oldest.
Optimise stats collection in KBucket to avoid creating new lists of all nodes.
https://github.com/ConsenSys/teku/issues/6371
> Use Guava cache for ExpirationSet to simplify and optimise implementation

- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
Fix a couple of potential memory leaks when tracking the latest nonce for sessions.
1. A race condition could mean that a previous nonce generation hadn't yet been registered with `NodeSessionManager` before a second generation tried to replace it. This would result in both nonces being tracked with the older one never being removed and retaining a reference to the `NodeSession` permanently.
2. A `NodeSession` may be removed from `NodeSessionManager` while still in use for processing a packet which then causes it to generate a new nonce. The new nonce would be added to `NodeSessionManager` after it cleaned up the "last nonce" and would wind up being tracked after the `NodeSession` had expired leading to a memory leak.
> Fix potential memory leak in tracking of session nonces

- src/main/java/org/ethereum/beacon/discovery/AddressAccessPolicy.java
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/HandshakeMessagePacketHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/OutgoingParcelHandler.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/PacketSourceFilter.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandler.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/handler/OutgoingParcelHandlerTest.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/handler/PacketSourceFilterTest.java
- src/test/java/org/ethereum/beacon/discovery/pipeline/info/FindNodeResponseHandlerTest.java
Implements an address access policy to allow library users to restrict which IP addresses are allowed for incoming and outgoing packets as well as for accepted node records.
https://github.com/ConsenSys/teku/issues/6242
> Implement source address filtering

- src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
- src/test/java/org/ethereum/beacon/discovery/schema/NodeSessionTest.java
I'm not sure this can actually happen easily, but added guards around map entries coming back empty etc. given they're closing down we'll just log debug messages.
fixes #173
> Fixed NPE in node session

- .circleci/config.yml
- src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/network/DiscoveryServer.java
- src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryClientImpl.java
- src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryServerImpl.java
- src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaInterpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
- src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
- src/test/java/org/ethereum/beacon/discovery/SimpleIdentitySchemaInterpreter.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java
- Allow to pass multiple listen addresses and ports
- Expose `IPv6` methods in `NodeRecord`
Change CircleCI to use machine executor instead of docker as per https://circleci.com/docs/faq/#ipv6-in-tests
fixes  #176
> Support listening both IPv4 and IPv6 + NodeRecord extension

- build.gradle
- gradle/versions.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/message/handler/DefaultExternalAddressSelector.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
- src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java
- Upgrade ilbraries + gradle
- Align usage of `NewAddressHandler` to be compatible when using both IPv4 and IPv6
related to #176
> IPv4/IPv6 additional handling + dependencies updates

- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaInterpreter.java
- src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
- src/test/java/org/ethereum/beacon/discovery/SimpleIdentitySchemaInterpreter.java
- src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java
Needed for [teku#](https://github.com/Consensys/teku/pull/8641)
See https://github.com/zilm13/teku/blob/507ff36602bd68fac788e0d64748b407aedb5db4/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/discovery/discv5/NodeRecordConverter.java#L41-L47
> Expose IdentitySchemaInterpreter.calculateNodeId

- build.gradle
- gradle/versions.gradle
> Update tuweni library.

- src/main/java/org/ethereum/beacon/discovery/DiscoverySystem.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
- src/main/java/org/ethereum/beacon/discovery/DiscoverySystemImpl.java
- src/main/java/org/ethereum/beacon/discovery/MutableDiscoverySystem.java
- src/main/java/org/ethereum/beacon/discovery/storage/KBucket.java
- src/main/java/org/ethereum/beacon/discovery/storage/KBuckets.java
- src/test/java/org/ethereum/beacon/discovery/app/DiscoveryTestServer.java
- src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/KBucketTest.java
- src/test/java/org/ethereum/beacon/discovery/storage/KBucketsTest.java
Add some methods to aid in the development of the Samba portal client library.
https://github.com/Consensys/discovery/issues/186
> Add getNodeRecordBuckets, addNodeRecord, and deleteNode to DiscoverySystem
