Consensys/discovery

src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTableImpl.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkInteropTest.java
src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java

Enable findClosestNodes to dump the entire discovered peer table

Discovery integration

---

gradle.properties

Update version for the 0.1.0 release.

0.1.0 release

---

gradle.properties

Update version for next release cycle.

Prep for next release cycle

---

src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java

Adds a simple method to `NodeRecord` to create a new record from private key, ip and port.

Add NodeRecord.createNodeRecord

---

build.gradle
gradle/versions.gradle
src/main/java/org/ethereum/beacon/discovery/network/NettyDiscoveryServerImpl.java
src/main/java/org/ethereum/beacon/discovery/packet/AbstractPacket.java
src/main/java/org/ethereum/beacon/discovery/packet/Packet.java
src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouSessionResolver.java
src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java
src/test/java/org/ethereum/beacon/discovery/FunctionsTest.java
src/test/resources/log4j2.xml

A few minor tidy ups to make working with the code base and tests easier:
* Add log4j-slf4j-impl dependency to test runtime so SLF4J log messages are handled.
* Add a netty logging handler to record (at trace level) all sent and received messages
* Remove unused code
* Add `@SafeVarargs` to DiscoveryTaskManager constructor
* Add test vectors from the spec
* Default to trace logging in tests

Minor tidy ups

---

gradle.properties

Set version to 0.3.1-SNAPSHOT in preparation for continuing development.

Prep for 0.3.1 release cycle

---

src/main/java/org/ethereum/beacon/discovery/task/LiveCheckTasks.java

`LiveCheckTasks` was using nanos to specify the timeout but that may overflow, so use seconds instead.
Also add a trace log when a liveness check fails.

Fix timeout in LiveCheckTasks

---

src/main/java/org/ethereum/beacon/discovery/DiscoveryManager.java
src/main/java/org/ethereum/beacon/discovery/DiscoveryManagerImpl.java
src/main/java/org/ethereum/beacon/discovery/DiscoverySystem.java
src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaInterpreter.java
src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordBuilder.java
src/main/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStore.java
src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
src/test/java/org/ethereum/beacon/discovery/SimpleIdentitySchemaInterpreter.java
src/test/java/org/ethereum/beacon/discovery/integration/DiscoveryIntegrationTest.java
src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java

Adds a custom field to Node Record object and API to update it through Discovery System.

Add custom field to Node Record

---

src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java

Small nit left from the previous PR. https://github.com/PegaSysEng/discovery/pull/36

Change method name

---

src/main/java/org/ethereum/beacon/discovery/storage/NodeTableImpl.java
src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java

Fixes the exception reported in https://github.com/PegaSysEng/teku/issues/1792
Handles node table lookups that don't find the entry in question (it may have been removed in the meantime safely) and ensure that the TaskManager executes recursive searches on it's task thread preserving the correct threading model.

Handle Optionals safely

---

src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeIdToSession.java
src/test/java/org/ethereum/beacon/discovery/pipeline/handler/NodeIdToSessionTest.java

When we don't have a destination UDP address, no session can be created. Just ignore requests instead of throwing `NoSuchElementException`.
fixes #56

Ignore requests when a session can't be created instead of failing

---

build.gradle

Need to make sure the jar version and the artifact version are in sync when publishing to bintray.

Publish jar with correct version in name

---

src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
src/main/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStore.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeRecordListener.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
src/test/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelectorTest.java
src/test/java/org/ethereum/beacon/discovery/pipeline/handler/NodeIdToSessionTest.java
src/test/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStoreTest.java

Address the case when the client code needs to be notified on the local ENR updates. 
the part of https://github.com/PegaSysEng/teku/pull/2715

Add local ENR change listener

---

build.gradle
gradle/versions.gradle
src/main/java/org/ethereum/beacon/discovery/type/DelegateBytes.java

Upgrading library to use latest 1.3.0 version of tuweni libraries.

Update to tuweni version 1.3.0; remove unnecessary tuweni libraries

---

src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
src/main/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStore.java
src/main/java/org/ethereum/beacon/discovery/storage/NewAddressHandler.java
src/main/java/org/ethereum/beacon/discovery/storage/NewAddressListener.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
src/test/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelectorTest.java
src/test/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManagerTest.java
src/test/java/org/ethereum/beacon/discovery/storage/LocalNodeRecordStoreTest.java

Provide callback to change node record on new address

Provide callback to change node record on new address

---

.circleci/config.yml
build.gradle

Switch publishing to cloudsmith instead of bintray.

Switch publishing to cloudsmith

---

gradle/versions.gradle
src/main/java/org/ethereum/beacon/discovery/TalkHandler.java
src/main/java/org/ethereum/beacon/discovery/database/LinkedDataSource.java
src/main/java/org/ethereum/beacon/discovery/database/XorKeyDatabase.java
src/main/java/org/ethereum/beacon/discovery/message/handler/ExternalAddressSelector.java
src/main/java/org/ethereum/beacon/discovery/packet/impl/AbstractBytes.java
src/main/java/org/ethereum/beacon/discovery/packet/impl/MessagePacketImpl.java
src/main/java/org/ethereum/beacon/discovery/packet/impl/PacketImpl.java
src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NodeSessionManager.java
src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouPacketHandler.java
src/main/java/org/ethereum/beacon/discovery/scheduler/Schedulers.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeSession.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeBucket.java
src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java
src/main/java/org/ethereum/beacon/discovery/util/RlpUtil.java
src/main/java/org/ethereum/beacon/discovery/util/Utils.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
src/test/java/org/ethereum/beacon/discovery/TestUtil.java
src/test/java/org/ethereum/beacon/discovery/message/handler/FindNodeHandlerTest.java

update errorprone to 2.4.0, and action the issues raised by the version update.

Errorprone update

---

src/main/java/org/ethereum/beacon/discovery/pipeline/handler/WhoAreYouPacketHandler.java

It actually appears fairly frequently and there's nothing that can be done to rectify the issue, so it's closer to a debug level message than an actual error that someone can take steps to rectify.
fixes #92
Signed-off-by: Paul Harris <paul.harris@consensys.net>

Change verification not passed message to debug level output

---

src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTable.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTableImpl.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorage.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorageFactory.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorageFactoryImpl.java
src/main/java/org/ethereum/beacon/discovery/storage/NodeTableStorageImpl.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryInteropTest.java
src/test/java/org/ethereum/beacon/discovery/DiscoveryNetworkTest.java
src/test/java/org/ethereum/beacon/discovery/HandshakeHandlersTest.java
src/test/java/org/ethereum/beacon/discovery/storage/NodeTableTest.java

`NodeTable` doesn't actually need a reference to the home node so remove it and simplify things.

Remove home node from NodeTable

---

build.gradle
gradle/versions.gradle

Upgrade log4j to 2.15.0

---

src/main/java/org/ethereum/beacon/discovery/storage/KBuckets.java

Fixes an issue where a `KBucket` was accessed outside of the `synchronized` methods in `KBuckets` because of the way streams use lazy evaluation.
Alternative to #134 
fixes #125

Fix concurrent access to KBucket

---

src/main/java/org/ethereum/beacon/discovery/util/Functions.java

Creating `SecureRandom` every time is performance expensive ('eats' around 10% of overall discovery) and may potentially have security issues

Create and use a single `SecureRandom` instance

---

gradle/versions.gradle

Upgrade to log4j 2.17.1

---

.github/workflows/gradle-wrapper-validation.yml
gradle/wrapper/gradle-wrapper.properties

Updates to gradle 7.4 and adds a validation step that gradle wrapper jar is from an official release.

Update to gradle 7.4

---

src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
src/main/java/org/ethereum/beacon/discovery/task/DiscoveryTaskManager.java

Add a bit more configuration capability for discovery system

Make `recursiveLookupInterval` configurable

---

.gitignore
gradle/check-licenses.gradle
src/main/java/org/ethereum/beacon/discovery/format/SerializerFactory.java
src/main/java/org/ethereum/beacon/discovery/message/MessageCode.java
src/main/java/org/ethereum/beacon/discovery/message/handler/DefaultExternalAddressSelector.java
src/main/java/org/ethereum/beacon/discovery/pipeline/handler/NewTaskHandler.java
src/main/java/org/ethereum/beacon/discovery/scheduler/Scheduler.java
src/main/java/org/ethereum/beacon/discovery/schema/DiscoveryProtocol.java
src/main/java/org/ethereum/beacon/discovery/schema/EnrField.java
src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchema.java
src/main/java/org/ethereum/beacon/discovery/schema/IdentityScheme.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeStatus.java
src/main/java/org/ethereum/beacon/discovery/storage/KBucket.java
src/main/java/org/ethereum/beacon/discovery/util/Utils.java

Fixing some things that IntelliJ recommended:
* Fix a bunch of little typos.
* Remove duplicate `*.swp` entry from `.gitignore` (it's also on line 2).
* Remove block of commented out code.
* Make private fields in enums final.
* Simplify `Utils#optionalFlatMap` method.

Fix some miscellaneous things

---

src/main/java/org/ethereum/beacon/discovery/util/Functions.java

I think this version is...
*  easier to understand,
* matches the description in the method comment,
* and is most likely faster.

Simplify logDistance function

---

src/main/java/org/ethereum/beacon/discovery/DiscoverySystemBuilder.java
src/main/java/org/ethereum/beacon/discovery/schema/EnrField.java
src/main/java/org/ethereum/beacon/discovery/schema/EnrFieldInterpreterV4.java
src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaInterpreter.java
src/main/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4Interpreter.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeRecord.java
src/main/java/org/ethereum/beacon/discovery/schema/NodeRecordBuilder.java
src/test/java/org/ethereum/beacon/discovery/NodeRecordTest.java
src/test/java/org/ethereum/beacon/discovery/SimpleIdentitySchemaInterpreter.java
src/test/java/org/ethereum/beacon/discovery/schema/IdentitySchemaV4InterpreterTest.java

Related to https://github.com/ethereum/consensus-specs/pull/3644 and https://github.com/ethereum/consensus-specs/pull/3874
N/A

Add QUIC support
